#!/bin/bash
# .claude/hooks/protect-files.sh
#
# Fires on PreToolUse for Edit and Write. Blocks edits to protected files:
# .env files (secrets), lockfiles (regenerated by package managers).
#
# Exits 2 with a reason in stderr to block the edit. Exits 0 otherwise.
#
# Register in .claude/settings.json under hooks.PreToolUse with matcher
# "Edit|Write".

set -u

# Fail closed. If jq is missing or the payload will not parse, we cannot tell
# whether this edit targets a protected file, so refuse it rather than wave it
# through. Previously both cases left FILE_PATH empty and exited 0, which meant
# a machine without jq silently disabled this hook entirely.
if ! command -v jq >/dev/null 2>&1; then
  echo "protect-files: jq not found, cannot evaluate this edit. Refusing (fail closed). Install jq." >&2
  exit 2
fi

INPUT=$(cat)

if ! FILE_PATH=$(printf '%s' "$INPUT" | jq -re '.tool_input.file_path // ""'); then
  echo "protect-files: could not parse hook input. Refusing (fail closed)." >&2
  exit 2
fi

# A genuinely absent file_path (a tool call that does not target a file) is fine.
[ -z "$FILE_PATH" ] && exit 0

# Get just the basename for cleaner pattern matching
BASENAME=$(basename "$FILE_PATH")

# Protected file patterns
case "$BASENAME" in
  .env|.env.*|*.env)
    echo "Refusing to edit protected file: $FILE_PATH (contains secrets)" >&2
    exit 2
    ;;
  package-lock.json|yarn.lock|bun.lock|bun.lockb|pnpm-lock.yaml|Cargo.lock|Gemfile.lock|poetry.lock|uv.lock|composer.lock|Pipfile.lock)
    echo "Refusing to edit lockfile: $FILE_PATH (run the package manager command instead)" >&2
    exit 2
    ;;
esac

exit 0
