/**
 * Builds the model-facing description for the `Workflow` orchestration tool.
 *
 * Dynamic in the agent's callable agents:
 * - lists every callable agent by name (the built-in `agent` plus one per
 *   declared subagent and remote agent);
 * - the worked example uses only the built-in `agent`, so it is valid for any
 *   agent;
 * - a single simple subagent example is appended *only when* the agent has a
 *   declared subagent or remote agent (i.e. an agent other than `agent`).
 *
 * The exact input signatures auto-generated by `createCodeModeTool` are appended
 * after this framing.
 *
 * @param toolNames - Names of the agent functions callable inside the sandbox.
 */
export function workflowToolDescription(toolNames: readonly string[]): string {
  const agents = toolNames.length > 0 ? toolNames : ["agent"];
  const list = agents.map((name) => `\`${name}\``).join(", ");
  const subagents = agents.filter((name) => name !== "agent");
  const subagentExample =
    subagents.length > 0
      ? `\n\nDeclared subagents are called the same way — e.g. \`const note = await tools.${subagents[0]}({ message: "..." });\`.`
      : "";

  return `Orchestrate this agent's subagents by writing a JavaScript program the runtime executes deterministically — fan out independent subtasks, run staged pipelines, and combine results in code, in a single step.

The only callable operations are these agents — no filesystem, network, shell, or other tools: ${list}. Call each as \`await tools.<name>(input)\`; it resolves to the child's result, or a typed object when you pass an \`outputSchema\`. Sequence with \`await\`, run agents concurrently with \`Promise.all([...])\`, and use \`map\`/\`filter\`/\`flatMap\` to build calls and combine results. The program's return value becomes the tool result.

Reach for this when work decomposes into independent or staged subtasks — map-reduce over a list, a plan-then-verify pipeline, or fan-out-and-gather. For a single delegation, call the agent directly.

Example — fan out across areas with \`agent\`, then pipe the results into a synthesis step:
\`\`\`js
const areas = ["correctness", "security", "performance"];
const reviews = await Promise.all(
  areas.map((area) =>
    tools.agent({
      message: \`Review the change for \${area}.\`,
      outputSchema: { type: "object", properties: { findings: { type: "array", items: { type: "string" } } } },
    }),
  ),
);
const verdict = await tools.agent({
  message: \`Summarize these findings into a verdict: \${JSON.stringify(reviews)}\`,
  outputSchema: { type: "object", properties: { verdict: { type: "string" }, blocking: { type: "boolean" } } },
});
return verdict;
\`\`\`${subagentExample}`;
}
