import { dirname, join, relative } from "node:path";

import type { CompiledAgentManifest, CompiledChannelDefinition } from "#compiler/manifest.js";

interface ChannelInstrumentationTypesSourceInput {
  readonly manifest: CompiledAgentManifest;
  readonly typesPath: string;
}

interface ChannelInstrumentationDeclaration {
  readonly exportName?: string;
  readonly importSpecifier: string;
  readonly kind: string;
}

export const CHANNEL_INSTRUMENTATION_TYPES_FILE_NAME = "channel-instrumentation-types.d.ts";

export function createChannelInstrumentationTypesSource(
  input: ChannelInstrumentationTypesSourceInput,
): string {
  const declarations = collectChannelInstrumentationDeclarations(input);
  const body =
    declarations.length === 0
      ? ["  interface ChannelMetadataMap {}", "  interface ChannelReferenceMap {}"]
      : [
          "  interface ChannelMetadataMap {",
          ...declarations.map(
            (declaration) =>
              `    readonly ${JSON.stringify(declaration.kind)}: InferChannelMetadata<${renderImportedChannelType(declaration)}>;`,
          ),
          "  }",
          "  interface ChannelReferenceMap {",
          ...declarations.map(
            (declaration) =>
              `    readonly ${JSON.stringify(declaration.kind)}: ${renderImportedChannelType(declaration)};`,
          ),
          "  }",
        ];

  return [
    "// Generated by Eve. Do not edit by hand.",
    'import type { InferChannelMetadata } from "eve/channels";',
    "",
    'declare module "eve/channels" {',
    ...body,
    "}",
    "",
  ].join("\n");
}

function collectChannelInstrumentationDeclarations(
  input: ChannelInstrumentationTypesSourceInput,
): ChannelInstrumentationDeclaration[] {
  const typesDirectory = dirname(input.typesPath);
  const declarationsByKind = new Map<string, ChannelInstrumentationDeclaration>();

  for (const channel of [...input.manifest.channels]
    .filter((entry): entry is CompiledChannelDefinition => entry.kind === "channel")
    .sort(compareCompiledChannels)) {
    const kind = `channel:${channel.name}`;

    if (declarationsByKind.has(kind)) {
      continue;
    }

    declarationsByKind.set(kind, {
      exportName: channel.exportName,
      importSpecifier: createChannelImportSpecifier({
        agentRoot: input.manifest.agentRoot,
        channel,
        fromDirectory: typesDirectory,
      }),
      kind,
    });
  }

  return [...declarationsByKind.values()];
}

function compareCompiledChannels(
  left: CompiledChannelDefinition,
  right: CompiledChannelDefinition,
): number {
  return (
    left.name.localeCompare(right.name) ||
    left.logicalPath.localeCompare(right.logicalPath) ||
    (left.exportName ?? "").localeCompare(right.exportName ?? "") ||
    left.sourceId.localeCompare(right.sourceId) ||
    left.method.localeCompare(right.method) ||
    left.urlPath.localeCompare(right.urlPath)
  );
}

function createChannelImportSpecifier(input: {
  readonly agentRoot: string;
  readonly channel: CompiledChannelDefinition;
  readonly fromDirectory: string;
}): string {
  const targetPath = join(input.agentRoot, toRuntimeImportLogicalPath(input.channel.logicalPath));
  const relativeSpecifier = relative(input.fromDirectory, targetPath).replaceAll("\\", "/");

  if (relativeSpecifier.startsWith(".")) {
    return relativeSpecifier;
  }

  return `./${relativeSpecifier}`;
}

function toRuntimeImportLogicalPath(logicalPath: string): string {
  if (logicalPath.endsWith(".mts")) {
    return `${logicalPath.slice(0, -".mts".length)}.mjs`;
  }

  if (logicalPath.endsWith(".cts")) {
    return `${logicalPath.slice(0, -".cts".length)}.cjs`;
  }

  if (logicalPath.endsWith(".ts")) {
    return `${logicalPath.slice(0, -".ts".length)}.js`;
  }

  return logicalPath;
}

function renderImportedChannelType(declaration: ChannelInstrumentationDeclaration): string {
  const exportName = declaration.exportName ?? "default";
  const importedModule = `import(${JSON.stringify(declaration.importSpecifier)})`;

  if (isIdentifierName(exportName)) {
    return `typeof ${importedModule}.${exportName}`;
  }

  return `typeof ${importedModule}[${JSON.stringify(exportName)}]`;
}

function isIdentifierName(value: string): boolean {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(value);
}
