import { describe, expect, it } from "vitest";

import {
  CHANNEL_INSTRUMENTATION_TYPES_FILE_NAME,
  createChannelInstrumentationTypesSource,
} from "#compiler/channel-instrumentation-types.js";
import {
  COMPILED_AGENT_MANIFEST_VERSION,
  createCompiledAgentManifest,
  type CompiledChannelEntry,
  type CompiledChannelDefinition,
} from "#compiler/manifest.js";
import type { ChannelMethod } from "#public/definitions/channel.js";

function createChannel(input: {
  readonly exportName?: string;
  readonly logicalPath: string;
  readonly method?: ChannelMethod;
  readonly name: string;
  readonly sourceId?: string;
  readonly urlPath?: string;
}): CompiledChannelDefinition {
  const channel: CompiledChannelDefinition = {
    kind: "channel",
    logicalPath: input.logicalPath,
    method: input.method ?? "POST",
    name: input.name,
    sourceId: input.sourceId ?? input.logicalPath,
    sourceKind: "module",
    urlPath: input.urlPath ?? `/${input.name}`,
  };

  if (input.exportName !== undefined) {
    return {
      ...channel,
      exportName: input.exportName,
    };
  }

  return channel;
}

function createManifest(channels: readonly CompiledChannelEntry[]) {
  return createCompiledAgentManifest({
    agentRoot: "/workspace/app/agent",
    appRoot: "/workspace/app",
    channels,
    config: {
      model: {
        contextWindowTokens: 128_000,
        id: "openai/gpt-5.4-mini",
        routing: { kind: "gateway", target: "openai" },
      },
      name: "test-agent",
    },
  });
}

describe("createChannelInstrumentationTypesSource", () => {
  it("emits deterministic ambient metadata map entries for authored channels", () => {
    const source = createChannelInstrumentationTypesSource({
      manifest: createManifest([
        createChannel({
          logicalPath: "channels/support.ts",
          method: "POST",
          name: "support",
          urlPath: "/support",
        }),
        createChannel({
          logicalPath: "channels/support.ts",
          method: "GET",
          name: "support",
          urlPath: "/support/events",
        }),
        {
          kind: "disabled",
          logicalPath: "channels/legacy.ts",
          name: "legacy",
        },
        createChannel({
          exportName: "opsChannel",
          logicalPath: "channels/ops.mts",
          name: "ops",
        }),
      ]),
      typesPath: `/workspace/app/.eve/compile/${CHANNEL_INSTRUMENTATION_TYPES_FILE_NAME}`,
    });

    expect(source).toBe(
      [
        "// Generated by Eve. Do not edit by hand.",
        'import type { InferChannelMetadata } from "eve/channels";',
        "",
        'declare module "eve/channels" {',
        "  interface ChannelMetadataMap {",
        '    readonly "channel:ops": InferChannelMetadata<typeof import("../../agent/channels/ops.mjs").opsChannel>;',
        '    readonly "channel:support": InferChannelMetadata<typeof import("../../agent/channels/support.js").default>;',
        "  }",
        "  interface ChannelReferenceMap {",
        '    readonly "channel:ops": typeof import("../../agent/channels/ops.mjs").opsChannel;',
        '    readonly "channel:support": typeof import("../../agent/channels/support.js").default;',
        "  }",
        "}",
        "",
      ].join("\n"),
    );
  });

  it("emits an empty declaration for agents without active channels", () => {
    const source = createChannelInstrumentationTypesSource({
      manifest: {
        ...createManifest([
          {
            kind: "disabled",
            logicalPath: "channels/support.ts",
            name: "support",
          },
        ]),
        version: COMPILED_AGENT_MANIFEST_VERSION,
      },
      typesPath: `/workspace/app/.eve/compile/${CHANNEL_INSTRUMENTATION_TYPES_FILE_NAME}`,
    });

    expect(source).toBe(
      [
        "// Generated by Eve. Do not edit by hand.",
        'import type { InferChannelMetadata } from "eve/channels";',
        "",
        'declare module "eve/channels" {',
        "  interface ChannelMetadataMap {}",
        "  interface ChannelReferenceMap {}",
        "}",
        "",
      ].join("\n"),
    );
  });
});
